import {
    geistSans,
    geistMono,
    almendraSc,
    montserrat,
    grenzeGotisch,
} from '@/ui/fonts';
import Navbar from '@/components/navbar/navbar';
import Footer from './components/footer/footer';

import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const links = [
    { id: 1, text: 'Home', href: '/' },
    { id: 2, text: 'About', href: '/about' },
    { id: 3, text: 'Contact', href: '/contact' },
];

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistMono.className} antialiased`}>
                <div className="fixed top-0 z-[-2] h-screen w-full bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))] hidden dark:block"></div>
                <div className="absolute top-0 z-[-2] h-screen w-screen bg-white bg-[radial-gradient(100%_50%_at_50%_0%,rgba(0,163,255,0.13)_0,rgba(0,163,255,0)_50%,rgba(0,163,255,0)_100%)] block dark:hidden"></div>
                <Navbar links={links} />
                {children}
                <Footer />
            </body>
        </html>
    );
}
